// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const image: string;
export const eye: string;
export const left: string;
export const right: string;
export const box: string;
export const pupil: string;
