// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const wrapper: string;
export const frontmatter: string;
export const title: string;
export const body: string;
