// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const titleblock: string;
export const sectionHeader: string;
export const hashtag: string;
export const title: string;
export const skillblock: string;
export const aboutBtns: string;
