// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const tableWrapper: string;
export const styledTable: string;
export const activeRow: string;
